/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./static/js/**/*.js",
    // Add explicit paths for container builds
    "/app/templates/**/*.html",
    "/app/static/js/**/*.js",
    // Include any dynamic classes referenced in your JS
    "./static/js/study.js",
    "./static/js/app.js"
  ],
  safelist: [
    // Add dark mode classes to safelist
    'dark:bg-gray-600',
    'dark:bg-gray-700', 
    'dark:bg-gray-800',
    'dark:bg-gray-900',
    'dark:text-white',
    'dark:text-gray-300',
    'dark:text-gray-400',
    'dark:text-gray-500',
    'dark:border-gray-700',
    'dark:shadow-gray-900/20',
    'dark:hover:bg-gray-700',
    'dark:hover:bg-gray-800',
    'dark:bg-red-600',
    'dark:hover:bg-red-700',
    'dark:bg-green-600', 
    'dark:hover:bg-green-700',
    'dark:bg-purple-900',
    'dark:text-purple-300',
    'dark:hover:bg-purple-800',
    'dark:bg-indigo-900',
    'dark:text-indigo-300',
    'dark:hover:bg-indigo-800',
    'dark:bg-red-500',
    'dark:bg-green-500',
    // Safelist dynamic classes that might not be detected by Tailwind scanner
    'bg-red-500',
    'bg-green-500', 
    'bg-blue-500',
    'bg-yellow-500',
    'text-white',
    'px-6',
    'py-4',
    'rounded-lg',
    'shadow-lg',
    'mb-3',
    'max-w-sm',
    'hidden',
    'flipped',
    'flip-horizontal',
    'flip-vertical-up',
    'flip-vertical-down',
    'opacity-50',
    'border-blue-400',
    'bg-blue-100',
    'text-blue-700',
    'border-blue-200',
    'bg-purple-100',
    'text-purple-700',
    'border-purple-200',
    'active',
    'open',
    'show',
    // Flashcard specific classes
    'flashcard',
    'flashcard-inner',
    'flashcard-front',
    'flashcard-back',
    'card-container',
    'nav-button',
    'edit-btn',
    'modal',
    'modal-backdrop',
    'modal-content',
    'keyboard-hints',
    // Mobile navigation classes
    'sidebar',
    'overlay',
    'hamburger',
    'main-content',
    'mobile-header',
    'stats-grid-mobile',
    'stats-card-mobile',
    'stats-icon',
    'stats-text',
    'stats-label',
    'stats-value',
    'mobile-page-header',
    'mobile-page-title',
    'mobile-page-subtitle'
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}